name: @name@
version: @version@
description: @description@
api-version: @apiVersion@
author: @author@
main: @main@
commands:
  global:
    aliases: [g]
    description: Manda uma mensagem para todos no servidor
    permission: surredstone.global
  village:
    aliases: [vil]
    description: Gerencia uma vila
    permission: surredstone.village
permissions:
  surredstone.*:
    default: op
    description: Todas as permissões do plugin
  surredstone.global: 
    default: true
    description: Executar o comando /global
  surredstone.village:
    default: true
    description: Executar o comando /village
  surredstone.village.*:
    default: op
    description: Executar todos os subcomandos do comando /village
  surredstone.village.info:
    default: true
    description: Executar o subcomando /village info
  surredstone.villages.*:
    default: op
    description: Permissões das vilas